# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('colour', models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('I', 'Indigo'), ('V', 'Violet')], max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('kingdom', models.CharField(choices=[('Eu', 'Eubacteria'), ('Ar', 'Archaebacteria'), ('Fu', 'Fungi'), ('Pl', 'Plantae'), ('An', 'Animalia')], max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('phylum', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('speciesId', models.AutoField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=50)),
                ('species', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, choices=[('I', 'Invertebrates'), ('V', 'Vertebrates')], max_length=1)),
                ('sillouette', models.ImageField(blank=True, upload_to='sillouettes/')),
                ('mechanism', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('I', 'Interference'), ('S', 'Scattering'), ('D', 'Diffraction')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('structure', models.CharField(blank=True, choices=[('1', '1D'), ('2', '2D'), ('3', '3D')], max_length=1)),
                ('tunable', models.CharField(blank=True, choices=[('A', 'Active'), ('P', 'Passive')], max_length=1)),
                ('wavelength', models.CharField(blank=True, max_length=15)),
                ('iridescense', models.BooleanField()),
                ('iridescense_factors', models.CharField(blank=True, max_length=20)),
                ('invisable_Signals', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('U', 'UV'), ('I', 'IR')], max_length=3)),
                ('presumable_Functions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Aposematism'), ('C', 'Crypsis'), ('S', 'Sexual'), ('O', 'Other')], max_length=7)),
                ('geography', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Am', 'Americas'), ('Eu', 'Europe'), ('Af', 'Africa'), ('As', 'Asia'), ('Oc', 'Oceania')], max_length=14)),
                ('ecosystem', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fo', 'Forest'), ('De', 'Desert'), ('Gr', 'Grassland'), ('Mo', 'Mountain'), ('Ma', 'Marine'), ('Fr', 'Freshwater')], max_length=17)),
                ('family', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Family')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Colour')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Species')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Species'),
        ),
        migrations.AddField(
            model_name='order',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Phylum'),
        ),
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
