# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171018_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='landingPictures/')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Species')),
            ],
        ),
    ]
