# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171109_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesClass',
            fields=[
                ('speciesClass', models.CharField(default='Unknown', max_length=50, primary_key=True, serialize=False)),
                ('phylum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Phylum')),
            ],
        ),
        migrations.RemoveField(
            model_name='speciescolour',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='speciescolour',
            name='species',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phylum',
        ),
        migrations.AddField(
            model_name='species',
            name='colour',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('I', 'Indigo'), ('V', 'Violet')], max_length=13),
        ),
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.DeleteModel(
            name='SpeciesColour',
        ),
        migrations.AddField(
            model_name='order',
            name='speciesClass',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='api.SpeciesClass'),
        ),
    ]
