# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171123_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
